export const GROUND_SIZE = 240
export const TILE = 4
export const ARENA_CLAMP = GROUND_SIZE / 2 - 2
export const PLAYER_Y = 1.7
export const PLAYER_RADIUS = 0.4
export const BASE_SPEED = 6.5
export const SPRINT_SPEED = 10.5
export const AIM_MULT = 0.55
export const FIXED_STEP = 1 / 60
export const MAX_DT = 0.05
export const MELEE_CD = 0.6
export const MELEE_RANGE = 3.0
export const SWITCH_CD = 0.35
export const GRENADE_FUSE = 1.5
export const GRENADE_RADIUS = 7
export const GRENADE_DMG = 120
export const PICKUP_MAGNET = 1.7
export const PICKUP_EXPIRY = 20
export const BEACON_MAX_HP = 1000
export const TIME_ATTACK_SECS = 180
